import type { Metadata } from 'next';

import '@/styles/reset.css';
import '@/styles/globals.css';
import '@/styles/theme.css';

import { pretendard } from '@/fonts/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={pretendard.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
